"""Export the trained ATE as synthesizable C++ for Vitis HLS 2022.1 (Part 2),
and prove that the exported C++ reproduces the Python reference exactly.

Emits into ../hls:
    ate_weights.h   constants: standardiser, int8 weights, log2 ROM, config
    ate_top.cpp     the whole report-rate engine, one report per call
    ate_top.h       interface
    ate_tb.cpp      testbench: reads vectors.csv, writes trig_hls.csv
    ap_stub.h       tiny stand-in for the vendor ap_* types so the same source
                    compiles with g++ for the equivalence check
"""

from __future__ import annotations
import os
import numpy as np

from gs2_core import (N_FEAT, LOG2_ROM, LOG2_ROM_N, LOG2_ROM_BITS, N_ACQ,
                      MS_SUBWIN, MS_NSUB, ALPHA_V, VBAR_HOLD_OCT, VBAR_HOLD_MAX,
                      DEAD_OCT, ALPHA_SLOW, MAX_DECAY, KAPPA_MIN_HI,
                      KAPPA_MAX_HI, KAPPA_MIN_LO, KAPPA_GAP_MIN, KAPPA_GAP_MAX,
                      FN, ATEM)


def _carr(name, a, fmt="%.10g", ctype="static const double"):
    a = np.asarray(a).ravel()
    body = ", ".join(fmt % v for v in a)
    return f"{ctype} {name}[{a.size}] = {{{body}}};\n"


def export(model, outdir, kappa_min_hi, wbits=8, qmeta=None):
    """`model` must be an ATEM (possibly wrapped by Biased)."""
    os.makedirs(outdir, exist_ok=True)
    beta_h = getattr(model, "beta_h", 0.0)
    beta_l = getattr(model, "beta_l", 0.0)
    m = getattr(model, "base", model)
    assert isinstance(m, ATEM), "exporter currently targets the ATE-M family"
    H = m.b1.size
    qmax = 2 ** (wbits - 1) - 1
    s1 = float(np.max(np.abs(m.W1))) / qmax
    s2 = float(np.max(np.abs(m.W2))) / qmax
    q1 = np.round(m.W1 / s1).astype(int)
    q2 = np.round(m.W2 / s2).astype(int)

    h = []
    h.append("// GENERATED by gs2_export.py -- do not edit by hand.\n")
    h.append("#ifndef ATE_WEIGHTS_H\n#define ATE_WEIGHTS_H\n\n")
    h.append(f"#define ATE_N_FEAT      {N_FEAT}\n")
    h.append(f"#define ATE_N_HIDDEN    {H}\n")
    h.append(f"#define ATE_W_BITS      {wbits}\n")
    h.append(f"#define ATE_N_MAC       {q1.size + q2.size}   "
             "// weight multiply-accumulates per report\n")
    h.append(f"#define ATE_N_SCALE_MUL {N_FEAT}   "
             "// standardiser multiplies (no divider anywhere)\n")
    h.append(f"#define ATE_LOG2_ROM_BITS {LOG2_ROM_BITS}\n")
    h.append(f"#define ATE_LOG2_ROM_N    {LOG2_ROM_N}\n")
    h.append(f"#define ATE_N_ACQ       {N_ACQ}\n")
    h.append(f"#define ATE_MS_SUBWIN   {MS_SUBWIN}\n")
    h.append(f"#define ATE_MS_NSUB     {MS_NSUB}\n")
    h.append(f"#define ATE_VBAR_HOLD_MAX {VBAR_HOLD_MAX}\n\n")
    h.append(f"static const double ATE_FN            = {FN!r};\n")
    h.append(f"static const double ATE_ALPHA_V       = {ALPHA_V!r};\n")
    h.append(f"static const double ATE_VBAR_HOLD_OCT = {VBAR_HOLD_OCT!r};\n")
    h.append(f"static const double ATE_DEAD_OCT      = {DEAD_OCT!r};\n")
    h.append(f"static const double ATE_ALPHA_SLOW    = {ALPHA_SLOW!r};\n")
    h.append(f"static const double ATE_MAX_DECAY     = {MAX_DECAY!r};\n")
    h.append(f"static const double ATE_KAPPA_MIN_HI  = {float(kappa_min_hi)!r};\n")
    h.append(f"static const double ATE_KAPPA_MAX_HI  = {KAPPA_MAX_HI!r};\n")
    h.append(f"static const double ATE_KAPPA_MIN_LO  = {KAPPA_MIN_LO!r};\n")
    h.append(f"static const double ATE_GAP_MIN       = {KAPPA_GAP_MIN!r};\n")
    h.append(f"static const double ATE_GAP_MAX       = {KAPPA_GAP_MAX!r};\n")
    h.append(f"static const double ATE_BETA_H        = {float(beta_h)!r};\n")
    h.append(f"static const double ATE_BETA_L        = {float(beta_l)!r};\n")
    h.append(f"static const double ATE_S1            = {s1!r};\n")
    h.append(f"static const double ATE_S2            = {s2!r};\n\n")
    h.append("// log2 mantissa ROM, addressed by the top "
             f"{LOG2_ROM_BITS} mantissa bits\n")
    h.append(_carr("ATE_LOG2_ROM", LOG2_ROM, "%.17g"))
    h.append("// standardiser: multiply by INV_SD, never divide\n")
    h.append(_carr("ATE_MEAN", m.mean, "%.17g"))
    h.append(_carr("ATE_INV_SD", m.inv_sd, "%.17g"))
    h.append(f"// layer 1 weights, int{wbits}, row-major [hidden][feature]\n")
    h.append(_carr("ATE_W1_Q", q1, "%d", "static const signed char"))
    h.append(_carr("ATE_B1", m.b1, "%.17g"))
    h.append(f"// layer 2 weights, int{wbits}, row-major [output][hidden]\n")
    h.append(_carr("ATE_W2_Q", q2, "%d", "static const signed char"))
    h.append(_carr("ATE_B2", m.b2, "%.17g"))
    rom_bits = q1.size * wbits + q2.size * wbits + \
        LOG2_ROM_N * 16 + (2 * N_FEAT + H + 2) * 16
    h.append(f"\n#define ATE_ROM_BITS  {rom_bits}  "
             "// int8 weights + 16-bit ROM/const storage\n")
    h.append("\n#endif\n")
    open(os.path.join(outdir, "ate_weights.h"), "w").write("".join(h))

    open(os.path.join(outdir, "ap_stub.h"), "w").write(AP_STUB)
    open(os.path.join(outdir, "ate_top.h"), "w").write(TOP_H)
    open(os.path.join(outdir, "ate_top.cpp"), "w").write(TOP_CPP)
    open(os.path.join(outdir, "ate_tb.cpp"), "w").write(TB_CPP)
    return dict(n_mac=int(q1.size + q2.size), n_scale_mul=N_FEAT,
                rom_bits=int(rom_bits), hidden=int(H), wbits=wbits,
                s1=s1, s2=s2)


AP_STUB = r"""// ap_stub.h -- stand-in for the Vitis ap_* types so that ate_top.cpp can be
// compiled with a host compiler for the software/hardware equivalence check.
// Vitis HLS uses <ap_fixed.h> instead; the algorithm text is identical.
#ifndef AP_STUB_H
#define AP_STUB_H
template <int W, int I> struct ap_fixed_stub {
    double v;
    ap_fixed_stub() : v(0) {}
    ap_fixed_stub(double x) : v(x) {}
    operator double() const { return v; }
};
#define ap_fixed ap_fixed_stub
typedef bool ap_uint1;
#endif
"""

TOP_H = r"""#ifndef ATE_TOP_H
#define ATE_TOP_H
#ifdef __SYNTHESIS__
#include <ap_fixed.h>
#else
#include "ap_stub.h"
#endif

typedef double ate_t;   // Part 2 replaces this with ap_fixed<W,I> per DSE point

// One report.  Returns the event flag.  All state is internal and static, so
// the call is a drop-in for the report-rate stage of the GridStream pipeline.
int ate_step(ate_t b, ate_t lv, ate_t fhz, int dead,
             ate_t *kappa_h_out, ate_t *kappa_l_out, ate_t *b_amb_out);
void ate_reset();
#endif
"""

TOP_CPP = r"""// GENERATED by gs2_export.py.  Report-rate Adaptive Threshold Engine.
//
// One call per synchrophasor report.  There is NO divider anywhere in this
// file and no multiplier between the goodness-of-fit input and the event flag:
// the trigger itself is an add and a compare.
#include "ate_top.h"
#include "ate_weights.h"

// ---------------------------------------------------------------- state ----
static double s_vbar;          // log2 reference magnitude
static int    s_held;
static int    s_vbar_init;

static double s_run_min;       // ambient tracker
static double s_cur_min;
static double s_ring[ATE_MS_NSUB];
static int    s_slot, s_filled, s_rcount;
static double s_b_amb;

static double s_m1, s_mad, s_dmax, s_jm, s_jf, s_prev_lv;   // features
static int    s_finit, s_lvinit;

static int    s_state;                                       // FSM
static double s_kh_l, s_kl_l, s_amb_l;

static const double BIG = 1e30;

void ate_reset() {
    s_vbar = 0; s_held = 0; s_vbar_init = 0;
    s_run_min = BIG; s_cur_min = BIG;
    for (int i = 0; i < ATE_MS_NSUB; i++) s_ring[i] = BIG;
    s_slot = 0; s_filled = 0; s_rcount = 0; s_b_amb = 0;
    s_m1 = 0; s_mad = 0; s_dmax = 0; s_jm = 0; s_jf = 0; s_prev_lv = 0;
    s_finit = 0; s_lvinit = 0;
    s_state = 0; s_kh_l = 0; s_kl_l = 0; s_amb_l = 0;
}

// ------------------------------------------------- log2: encoder + ROM ----
static double ate_log2(double x) {
    if (x <= 0.0) return -1023.0;
    int e = 0;
    double m = x;
    while (m >= 2.0) { m *= 0.5; e++; }     // priority encoder + barrel shift
    while (m < 1.0)  { m *= 2.0; e--; }
    int idx = (int)((m - 1.0) * (double)ATE_LOG2_ROM_N);
    if (idx < 0) idx = 0;
    if (idx >= ATE_LOG2_ROM_N) idx = ATE_LOG2_ROM_N - 1;
    return (double)e + ATE_LOG2_ROM[idx];
}

static double ate_abs(double x) { return x < 0.0 ? -x : x; }

// --------------------------------------------------------------- kernel ----
int ate_step(ate_t b_in, ate_t lv_in, ate_t fhz_in, int dead,
             ate_t *kappa_h_out, ate_t *kappa_l_out, ate_t *b_amb_out) {
#pragma HLS INLINE off
#pragma HLS PIPELINE II=1
    double b   = (double)b_in;
    double lv  = (double)lv_in;
    double fhz = (double)fhz_in;

    if (dead) {                              // de-energised: freeze everything
        *kappa_h_out = s_kh_l; *kappa_l_out = s_kl_l; *b_amb_out = s_b_amb;
        return s_state;
    }

    // prev_lv is seeded from the first LIVE report, not the first call, so that
    // the gated warm-up cannot enter the magnitude-jitter feature.
    if (!s_lvinit) { s_prev_lv = lv; s_lvinit = 1; }

    // ---- ambient tracker (minimum statistics), only while not asserted ----
    double amb;
    if (s_state == 0) {
        if (b < s_run_min) s_run_min = b;
        if (b < s_cur_min) s_cur_min = b;
        s_rcount++;
        if (s_rcount % ATE_MS_SUBWIN == 0) {
            s_ring[s_slot] = s_cur_min;
            s_slot = (s_slot + 1) % ATE_MS_NSUB;
            if (s_filled < ATE_MS_NSUB) s_filled++;
            s_cur_min = BIG;
        }
        if (s_rcount <= ATE_N_ACQ || s_filled == 0) {
            s_b_amb = s_run_min;
        } else {
            double mn = BIG;
            for (int i = 0; i < ATE_MS_NSUB; i++)
#pragma HLS UNROLL
                if (s_ring[i] < mn) mn = s_ring[i];
            if (s_cur_min < mn) mn = s_cur_min;
            s_b_amb = mn;
        }
        amb = s_b_amb;
    } else {
        amb = s_amb_l;                        // LATCHED while asserted
    }

    double excess = b - amb;

    // ---- six causal features, HELD while asserted ------------------------
    if (s_state == 0) {
        if (!s_finit) {
            s_m1 = excess; s_mad = 0.0; s_dmax = excess;
            s_jm = ate_abs(lv - s_prev_lv);
            s_jf = ate_abs(fhz - ATE_FN);
            s_finit = 1;
        } else {
            s_m1  += ATE_ALPHA_SLOW * (excess - s_m1);
            s_mad += ATE_ALPHA_SLOW * (ate_abs(excess - s_m1) - s_mad);
            double dec = s_dmax - ATE_MAX_DECAY;
            s_dmax = (excess > dec) ? excess : dec;
            s_jm  += ATE_ALPHA_SLOW * (ate_abs(lv - s_prev_lv) - s_jm);
            s_jf  += ATE_ALPHA_SLOW * (ate_abs(fhz - ATE_FN) - s_jf);
        }
        s_prev_lv = lv;
    }

    double f[ATE_N_FEAT];
    f[0] = amb;
    f[1] = s_m1;
    f[2] = s_mad;
    f[3] = s_dmax;
    f[4] = ate_log2(s_jm > 1e-9 ? s_jm : 1e-9);
    f[5] = ate_log2(s_jf > 1e-9 ? s_jf : 1e-9);

    // ---- ATE: standardise (multiply, never divide) then 6 -> H -> 2 ------
    double kh, gap;
    if (s_state == 0) {
        double z[ATE_N_FEAT];
        for (int i = 0; i < ATE_N_FEAT; i++)
#pragma HLS UNROLL
            z[i] = (f[i] - ATE_MEAN[i]) * ATE_INV_SD[i];

        double hdn[ATE_N_HIDDEN];
        for (int j = 0; j < ATE_N_HIDDEN; j++) {
            double acc = ATE_B1[j];
            for (int i = 0; i < ATE_N_FEAT; i++)
                acc += ((double)ATE_W1_Q[j * ATE_N_FEAT + i] * ATE_S1) * z[i];
            hdn[j] = acc > 0.0 ? acc : 0.0;          // ReLU
        }
        double y[2];
        for (int o = 0; o < 2; o++) {
            double acc = ATE_B2[o];
            for (int j = 0; j < ATE_N_HIDDEN; j++)
                acc += ((double)ATE_W2_Q[o * ATE_N_HIDDEN + j] * ATE_S2) * hdn[j];
            y[o] = acc;
        }
        kh  = y[0] + ATE_BETA_H;
        gap = y[1] + ATE_BETA_L;

        if (kh < ATE_KAPPA_MIN_HI) kh = ATE_KAPPA_MIN_HI;
        if (kh > ATE_KAPPA_MAX_HI) kh = ATE_KAPPA_MAX_HI;
        if (gap < ATE_GAP_MIN) gap = ATE_GAP_MIN;
        if (gap > ATE_GAP_MAX) gap = ATE_GAP_MAX;
    } else {
        kh = s_kh_l; gap = s_kh_l - s_kl_l;
    }

    double kl;
    if (s_state == 0) {
        kl = kh - gap;
        if (kl < ATE_KAPPA_MIN_LO) kl = ATE_KAPPA_MIN_LO;
    } else {
        kl = s_kl_l;
    }

    // ---- latched hysteresis FSM: one ADD and one COMPARE ----------------
    if (s_state == 0) {
        if (b >= amb + kh) { s_state = 1; s_kh_l = kh; s_kl_l = kl;
                             s_amb_l = amb; }
    } else {
        if (b < s_amb_l + s_kl_l) s_state = 0;
    }

    *kappa_h_out = kh; *kappa_l_out = kl; *b_amb_out = amb;
    return s_state;
}
"""

TB_CPP = r"""// ate_tb.cpp -- replays vectors.csv through ate_step and writes trig_hls.csv.
// Columns of vectors.csv: chan,b,lv,fhz,dead
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include "ate_top.h"

int main(int argc, char **argv) {
    const char *vin  = argc > 1 ? argv[1] : "vectors.csv";
    const char *vout = argc > 2 ? argv[2] : "trig_hls.csv";
    FILE *fi = fopen(vin, "r");
    if (!fi) { fprintf(stderr, "cannot open %s\n", vin); return 1; }
    FILE *fo = fopen(vout, "w");
    fprintf(fo, "chan,trig,kappa_h,kappa_l,b_amb\n");

    char line[512];
    if (!fgets(line, sizeof line, fi)) return 1;   // header
    int prev_chan = -1;
    long n = 0;
    while (fgets(line, sizeof line, fi)) {
        int chan, dead;
        double b, lv, fhz;
        if (sscanf(line, "%d,%lf,%lf,%lf,%d", &chan, &b, &lv, &fhz, &dead) != 5)
            continue;
        if (chan != prev_chan) { ate_reset(); prev_chan = chan; }
        ate_t kh, kl, amb;
        int t = ate_step(b, lv, fhz, dead, &kh, &kl, &amb);
        fprintf(fo, "%d,%d,%.17g,%.17g,%.17g\n", chan, t,
                (double)kh, (double)kl, (double)amb);
        n++;
    }
    fclose(fi); fclose(fo);
    fprintf(stderr, "ate_tb: %ld reports\n", n);
    return 0;
}
"""
