"""IEEE-format LaTeX tables, generated directly from the Part 1 CSVs.

Every number in ../out/tables.tex traces to a CSV in ../out.  Nothing is typed
by hand.
"""
from __future__ import annotations
import json, os, pickle, sys
import numpy as np
import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gs2_data as D

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.abspath(os.path.join(HERE, "..", "out"))
DATA = os.path.abspath(os.path.join(HERE, "..", "data"))


def esc(s):
    return (str(s).replace("&", r"\&").replace("%", r"\%").replace("_", r"\_")
            .replace("#", r"\#"))


def tabular(df, colfmt, header, rows, caption, label, note=None, width=None):
    env = "table*" if width == "double" else "table"
    out = [f"\\begin{{{env}}}[!t]", "\\centering",
           f"\\caption{{{caption}}}", f"\\label{{{label}}}",
           f"\\begin{{tabular}}{{{colfmt}}}", "\\hline",
           " & ".join(header) + r" \\", "\\hline"]
    out += [" & ".join(r) + r" \\" for r in rows]
    out += ["\\hline", "\\end{tabular}"]
    if note:
        out.append(f"\\\\[2pt]\\footnotesize {note}")
    out.append(f"\\end{{{env}}}")
    return "\n".join(out) + "\n\n"


def main():
    nums = json.load(open(os.path.join(OUT, "numbers.json")))
    st = pickle.load(open(os.path.join(OUT, "state.pkl"), "rb"))
    tex = ["% GENERATED by make_tables.py -- do not edit by hand.\n"]

    # ---- I. datasets ------------------------------------------------------
    ch = pd.read_csv(os.path.join(OUT, "table_channels.csv"))
    rows = []
    for rid in sorted(ch["rid"].unique()):
        rec = D.load_record(DATA, int(rid))
        sub = ch[ch["rid"] == rid]
        rows.append([str(rid), esc(rec["provider"]),
                     f"{sub['fs'].iloc[0]:.0f}", f"{sub['duration_s'].iloc[0]:.2f}",
                     str(int(sub["n_reports"].sum())),
                     str(int((sub["n_event_windows"] > 0).sum())) + "/6",
                     esc(rec["description"][:58] + "...")])
    tex.append(tabular(None, "llrrrrl",
                       ["ID", "Provider", "$f_s$ [Hz]", "$T$ [s]",
                        "channel-reports", "ch. w/ events", "GESL description"],
                       rows,
                       "GESL records used in Part~1. Six phase channels "
                       "(Va,Vb,Vc,Ia,Ib,Ic) are processed per record.",
                       "tab:datasets", width="double"))

    # ---- II. provenance ---------------------------------------------------
    pv = pd.read_csv(os.path.join(OUT, "table_provenance.csv"))
    rows = [[esc(r.check), esc(r.value)] for r in pv.itertuples()
            if "time base" not in r.check]
    tex.append(tabular(None, "ll", ["check", "result"], rows,
                       "Provenance checks against the GridStream-v1 reference. The FIR "
                       "row is a transcription defect in the v1 array, not a "
                       "design mismatch: three taps are duplicated or dropped, "
                       "breaking linear phase and costing 0.79\\% of DC gain.",
                       "tab:provenance", width="double"))

    # ---- III. method comparison ------------------------------------------
    agg = pd.read_csv(os.path.join(OUT, "table_aggregate.csv"), index_col=0)
    order = [("v1-fixed (TH=1e7, TL=300)", "v1 fixed thresholds, transported", ""),
             ("empirical-Q (causal)", "causal empirical quantile", ""),
             ("fixed margin (tuned on synthetic)",
              "fixed margin, tuned on synthetic", ""),
             ("ATE-Q int8, floor=hard", "ATE-Q int8 $+$ floor", ""),
             ("ATE-S int8, floor=hard", "ATE-S int8 $+$ floor", ""),
             ("ATE-M int8, floor=hard", "ATE-M int8 $+$ floor (deployed)", "*"),
             ("ATE-M int8 (leave-one-record-out)",
              "ATE-M int8, leave-one-record-out", ""),
             ("fixed margin (best constant, offline oracle)",
              "best constant, chosen in hindsight", "$\\dagger$"),
             ("per-channel statistical (offline oracle)",
              "per-channel ambient quantile", "$\\dagger$"),
             ("hindsight ceiling (offline oracle)",
              "per-channel optimum in hindsight", "$\\dagger$")]
    rows = []
    for key, name, mark in order:
        if key not in agg.index:
            continue
        r = agg.loc[key]
        rows.append([name + mark,
                     f"{r['micro_f1']:.3f}", f"{r['macro_f1']:.3f}",
                     f"{r['precision']:.3f}", f"{r['recall']:.3f}",
                     f"{r['event_recall']:.3f}",
                     f"{int(r['false_alarm_runs_quiet'])}",
                     f"{r['duty_cycle']:.3f}",
                     f"{1.0/r['duty_cycle']:.1f}" if r["duty_cycle"] > 0 else "--",
                     f"{r['latency_ms']:.1f}"])
    tex.append(tabular(None, "lrrrrrrrrr",
                       ["method", "micro $F_1$", "macro $F_1$", "prec.",
                        "recall", "ev. rec.", "FA$_q$", "duty",
                        "BW red.", "lat. [ms]"], rows,
                       "Report-level behaviour on the six GESL records "
                       "(36 channels, "
                       f"{nums['gesl']['n_reports']} valid reports). "
                       "FA$_q$ counts spurious trigger runs on the "
                       f"{36 - nums['gesl']['n_channels_with_events']} channels "
                       "with no reference event.",
                       "tab:methods",
                       note="*selected on held-out synthetic data before the "
                            "GESL records were scored. "
                            "$\\dagger$offline oracles: they use the reference "
                            "labels and are upper bounds, not methods.",
                       width="double"))

    # ---- IV. per record ---------------------------------------------------
    pr = pd.read_csv(os.path.join(OUT, "table_per_record_f1.csv"), index_col=0)
    cols = [c for c in ["v1-fixed (TH=1e7, TL=300)",
                        "fixed margin (tuned on synthetic)",
                        "ATE-Q int8, floor=hard", "ATE-S int8, floor=hard",
                        "ATE-M int8, floor=hard",
                        "ATE-M int8 (leave-one-record-out)",
                        "hindsight ceiling (offline oracle)"] if c in pr.columns]
    short = {"v1-fixed (TH=1e7, TL=300)": "v1 fixed",
             "fixed margin (tuned on synthetic)": "fixed margin",
             "ATE-Q int8, floor=hard": "ATE-Q",
             "ATE-S int8, floor=hard": "ATE-S",
             "ATE-M int8, floor=hard": "ATE-M (deployed)",
             "ATE-M int8 (leave-one-record-out)": "ATE-M LORO",
             "hindsight ceiling (offline oracle)": "ceiling$\\dagger$"}
    rows = [[str(i)] + [f"{pr.loc[i, c]:.3f}" for c in cols] for i in pr.index]
    tex.append(tabular(None, "l" + "r" * len(cols),
                       ["record"] + [short[c] for c in cols], rows,
                       "Mean report-level $F_1$ per record, over that record's "
                       "channels that contain a reference event.",
                       "tab:perrecord", width="double"))

    # ---- V. calibration speed --------------------------------------------
    cd = pd.read_csv(os.path.join(OUT, "table_calibration_speed.csv"))
    cols = [c for c in cd.columns if c != "horizon_s"]
    rows = [[f"{r.horizon_s:g}"] + [f"{getattr(r, c.replace(' ', '_').replace('-', '_')):.3f}"
                                    if hasattr(r, c.replace(' ', '_').replace('-', '_'))
                                    else f"{cd.loc[r.Index, c]:.3f}" for c in cols]
            for r in cd.itertuples()]
    tex.append(tabular(None, "l" + "r" * len(cols),
                       ["horizon [s]"] + [esc(c) for c in cols], rows,
                       "Calibration speed: mean absolute error of the predicted "
                       "$\\kappa_H$ against the required margin, on held-out "
                       "synthetic channels.", "tab:calibration"))

    # ---- VI. floor study --------------------------------------------------
    fs = pd.read_csv(os.path.join(OUT, "table_floor_sweep_gesl.csv"))
    keep = fs[fs["floor"].isin([0.0, 0.5, 1.0, 2.0, 3.0, 3.25, 3.75, 5.0])]
    rows = [[f"{r.floor:.2f}", f"{r.ate_micro:.3f}", f"{r.ate_macro:.3f}",
             f"{int(r.ate_fa_quiet)}", f"{r.ate_duty:.3f}",
             f"{r.const_micro:.3f}", f"{r.const_macro:.3f}",
             f"{int(r.const_fa_quiet)}", f"{r.const_duty:.3f}"]
            for r in keep.itertuples()]
    tex.append(tabular(None, "lrrrrrrrr",
                       ["$\\kappa_H$ floor", "micro $F_1$", "macro $F_1$",
                        "FA$_q$", "duty", "micro $F_1$", "macro $F_1$",
                        "FA$_q$", "duty"], rows,
                       "Effect of the physical floor. Left block: the deployed "
                       "ATE-M with that floor. Right block: a constant margin "
                       "equal to that floor. The learned margins matter most "
                       "when the floor is low.", "tab:floor",
                       note="Sensitivity analysis on the test records; the "
                            "deployed floor $\\log_2 10 = 3.32$ was fixed on "
                            "held-out synthetic data beforehand.",
                       width="double"))

    # ---- VII. equivalence -------------------------------------------------
    eq = pd.read_csv(os.path.join(OUT, "table_equivalence_summary.csv")).iloc[0]
    rows = [["reports replayed", f"{int(eq['reports'])}"],
            ["channels", f"{int(eq['channels'])}"],
            ["trigger mismatches", f"{int(eq['mismatches'])}"],
            ["max $|\\Delta b_{amb}|$", f"{eq['max_abs_db_amb']:.1e}"],
            ["max $|\\Delta\\kappa_H|$", f"{eq['max_abs_dkappa_h']:.1e}"],
            ["weight MACs per report", f"{int(eq['n_mac'])}"],
            ["standardiser multiplies", f"{int(eq['n_scale_mul'])}"],
            ["dividers on the trigger path", "0"],
            ["constant storage [bits]", f"{int(eq['rom_bits'])}"]]
    tex.append(tabular(None, "lr", ["quantity", "value"], rows,
                       "Exported C++ against the Python reference. This is "
                       "algorithm equivalence, not bit-exactness: the "
                       "\\texttt{ap\\_*} stub maps the fixed-point types to "
                       "\\texttt{double}.", "tab:equiv"))

    # ---- VIII. oracle validation -----------------------------------------
    ov = pd.read_csv(os.path.join(OUT, "table_oracle_validation.csv")).iloc[0]
    rows = [["environments / channels",
             f"{int(ov['n_environments'])} / {int(ov['n_channels'])}"],
            ["precision vs.\\ any injected disturbance",
             f"{ov['precision_vs_any_injected']:.2f}"],
            ["precision, windows padded by the response support",
             f"{ov['precision_vs_padded_injected']:.2f}"],
            ["report recall vs.\\ major injected events",
             f"{ov['report_recall_vs_major']:.2f}"],
            ["window recall vs.\\ major injected events",
             f"{ov['window_recall_vs_major']:.2f}"]]
    tex.append(tabular(None, "lr", ["quantity", "value"], rows,
                       "The reference oracle measured against synthetic ground "
                       "truth. It is imperfect, so every GESL trigger metric is "
                       "a comparison between methods on a common reference, not "
                       "an absolute detection rate.", "tab:oracle"))

    path = os.path.join(OUT, "tables.tex")
    open(path, "w").write("\n".join(tex))
    print("wrote", path, f"({len(tex)-1} tables)")


if __name__ == "__main__":
    main()
