// GENERATED by gs2_export.py.  Report-rate Adaptive Threshold Engine.
//
// One call per synchrophasor report.  There is NO divider anywhere in this
// file and no multiplier between the goodness-of-fit input and the event flag:
// the trigger itself is an add and a compare.
#include "ate_top.h"
#include "ate_weights.h"

// ---------------------------------------------------------------- state ----
static double s_vbar;          // log2 reference magnitude
static int    s_held;
static int    s_vbar_init;

static double s_run_min;       // ambient tracker
static double s_cur_min;
static double s_ring[ATE_MS_NSUB];
static int    s_slot, s_filled, s_rcount;
static double s_b_amb;

static double s_m1, s_mad, s_dmax, s_jm, s_jf, s_prev_lv;   // features
static int    s_finit, s_lvinit;

static int    s_state;                                       // FSM
static double s_kh_l, s_kl_l, s_amb_l;

static const double BIG = 1e30;

void ate_reset() {
    s_vbar = 0; s_held = 0; s_vbar_init = 0;
    s_run_min = BIG; s_cur_min = BIG;
    for (int i = 0; i < ATE_MS_NSUB; i++) s_ring[i] = BIG;
    s_slot = 0; s_filled = 0; s_rcount = 0; s_b_amb = 0;
    s_m1 = 0; s_mad = 0; s_dmax = 0; s_jm = 0; s_jf = 0; s_prev_lv = 0;
    s_finit = 0; s_lvinit = 0;
    s_state = 0; s_kh_l = 0; s_kl_l = 0; s_amb_l = 0;
}

// ------------------------------------------------- log2: encoder + ROM ----
static double ate_log2(double x) {
    if (x <= 0.0) return -1023.0;
    int e = 0;
    double m = x;
    while (m >= 2.0) { m *= 0.5; e++; }     // priority encoder + barrel shift
    while (m < 1.0)  { m *= 2.0; e--; }
    int idx = (int)((m - 1.0) * (double)ATE_LOG2_ROM_N);
    if (idx < 0) idx = 0;
    if (idx >= ATE_LOG2_ROM_N) idx = ATE_LOG2_ROM_N - 1;
    return (double)e + ATE_LOG2_ROM[idx];
}

static double ate_abs(double x) { return x < 0.0 ? -x : x; }

// --------------------------------------------------------------- kernel ----
int ate_step(ate_t b_in, ate_t lv_in, ate_t fhz_in, int dead,
             ate_t *kappa_h_out, ate_t *kappa_l_out, ate_t *b_amb_out) {
#pragma HLS INLINE off
#pragma HLS PIPELINE II=1
    double b   = (double)b_in;
    double lv  = (double)lv_in;
    double fhz = (double)fhz_in;

    if (dead) {                              // de-energised: freeze everything
        *kappa_h_out = s_kh_l; *kappa_l_out = s_kl_l; *b_amb_out = s_b_amb;
        return s_state;
    }

    // prev_lv is seeded from the first LIVE report, not the first call, so that
    // the gated warm-up cannot enter the magnitude-jitter feature.
    if (!s_lvinit) { s_prev_lv = lv; s_lvinit = 1; }

    // ---- ambient tracker (minimum statistics), only while not asserted ----
    double amb;
    if (s_state == 0) {
        if (b < s_run_min) s_run_min = b;
        if (b < s_cur_min) s_cur_min = b;
        s_rcount++;
        if (s_rcount % ATE_MS_SUBWIN == 0) {
            s_ring[s_slot] = s_cur_min;
            s_slot = (s_slot + 1) % ATE_MS_NSUB;
            if (s_filled < ATE_MS_NSUB) s_filled++;
            s_cur_min = BIG;
        }
        if (s_rcount <= ATE_N_ACQ || s_filled == 0) {
            s_b_amb = s_run_min;
        } else {
            double mn = BIG;
            for (int i = 0; i < ATE_MS_NSUB; i++)
#pragma HLS UNROLL
                if (s_ring[i] < mn) mn = s_ring[i];
            if (s_cur_min < mn) mn = s_cur_min;
            s_b_amb = mn;
        }
        amb = s_b_amb;
    } else {
        amb = s_amb_l;                        // LATCHED while asserted
    }

    double excess = b - amb;

    // ---- six causal features, HELD while asserted ------------------------
    if (s_state == 0) {
        if (!s_finit) {
            s_m1 = excess; s_mad = 0.0; s_dmax = excess;
            s_jm = ate_abs(lv - s_prev_lv);
            s_jf = ate_abs(fhz - ATE_FN);
            s_finit = 1;
        } else {
            s_m1  += ATE_ALPHA_SLOW * (excess - s_m1);
            s_mad += ATE_ALPHA_SLOW * (ate_abs(excess - s_m1) - s_mad);
            double dec = s_dmax - ATE_MAX_DECAY;
            s_dmax = (excess > dec) ? excess : dec;
            s_jm  += ATE_ALPHA_SLOW * (ate_abs(lv - s_prev_lv) - s_jm);
            s_jf  += ATE_ALPHA_SLOW * (ate_abs(fhz - ATE_FN) - s_jf);
        }
        s_prev_lv = lv;
    }

    double f[ATE_N_FEAT];
    f[0] = amb;
    f[1] = s_m1;
    f[2] = s_mad;
    f[3] = s_dmax;
    f[4] = ate_log2(s_jm > 1e-9 ? s_jm : 1e-9);
    f[5] = ate_log2(s_jf > 1e-9 ? s_jf : 1e-9);

    // ---- ATE: standardise (multiply, never divide) then 6 -> H -> 2 ------
    double kh, gap;
    if (s_state == 0) {
        double z[ATE_N_FEAT];
        for (int i = 0; i < ATE_N_FEAT; i++)
#pragma HLS UNROLL
            z[i] = (f[i] - ATE_MEAN[i]) * ATE_INV_SD[i];

        double hdn[ATE_N_HIDDEN];
        for (int j = 0; j < ATE_N_HIDDEN; j++) {
            double acc = ATE_B1[j];
            for (int i = 0; i < ATE_N_FEAT; i++)
                acc += ((double)ATE_W1_Q[j * ATE_N_FEAT + i] * ATE_S1) * z[i];
            hdn[j] = acc > 0.0 ? acc : 0.0;          // ReLU
        }
        double y[2];
        for (int o = 0; o < 2; o++) {
            double acc = ATE_B2[o];
            for (int j = 0; j < ATE_N_HIDDEN; j++)
                acc += ((double)ATE_W2_Q[o * ATE_N_HIDDEN + j] * ATE_S2) * hdn[j];
            y[o] = acc;
        }
        kh  = y[0] + ATE_BETA_H;
        gap = y[1] + ATE_BETA_L;

        if (kh < ATE_KAPPA_MIN_HI) kh = ATE_KAPPA_MIN_HI;
        if (kh > ATE_KAPPA_MAX_HI) kh = ATE_KAPPA_MAX_HI;
        if (gap < ATE_GAP_MIN) gap = ATE_GAP_MIN;
        if (gap > ATE_GAP_MAX) gap = ATE_GAP_MAX;
    } else {
        kh = s_kh_l; gap = s_kh_l - s_kl_l;
    }

    double kl;
    if (s_state == 0) {
        kl = kh - gap;
        if (kl < ATE_KAPPA_MIN_LO) kl = ATE_KAPPA_MIN_LO;
    } else {
        kl = s_kl_l;
    }

    // ---- latched hysteresis FSM: one ADD and one COMPARE ----------------
    if (s_state == 0) {
        if (b >= amb + kh) { s_state = 1; s_kh_l = kh; s_kl_l = kl;
                             s_amb_l = amb; }
    } else {
        if (b < s_amb_l + s_kl_l) s_state = 0;
    }

    *kappa_h_out = kh; *kappa_l_out = kl; *b_amb_out = amb;
    return s_state;
}
